name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
            poetry-version: "2.1.4"
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Ruff (lint)
        run: poetry run ruff check app tests

      - name: Run Black (format check)
        run: poetry run black --check app tests

      - name: Run Pytest
        run: poetry run pytest -v --maxfail=1 --disable-warnings
