name: Documentation Linting Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:
  
jobs:
  lint-documentation:
    runs-on: ubuntu-latest
    name: Lint Documentation
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'

    - name: Setup Java (for PlantUML)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: bash scripts/linting/install_deps.sh
      shell: bash
   
    - name: Lint Markdown files
      id: markdown-lint
      continue-on-error: true
      run: bash scripts/linting/lint_markdown.sh
      shell: bash

    - name: Check Markdown links
      id: link-check
      continue-on-error: true
      run: bash scripts/linting/check_links.sh
      shell: bash

    - name: Lint PlantUML files
      id: plantuml-lint
      continue-on-error: true
      run: bash scripts/linting/lint_plantuml.sh
      shell: bash

    - name: Generate final summary
      if: always()
      run: bash scripts/linting/generate_summary.sh
    
    - name: Upload linting artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: linting-results
        path: |
          *.log
          config/
        retention-days: 30